### ISSUE TITLE
L2Loss always returns Inf

### ISSUE THREAD

**Issue by verflieger** [SciML/DiffEqParamEstim.jl#183] opened 2022-11-04 09:47 UTC
I am trying to follow the tutorial example at https://docs.sciml.ai/DiffEqParamEstim/stable/tutorials/ODE_inference/

The loss function always returns Inf even though the sol.retcode is a ReturnCode.Success 

The problem seems to be the return code checking in 

https://github.com/SciML/DiffEqParamEstim.jl/blob/a4e00561d853d09dfc0dd8fd19e4495f489a8982/src/cost_functions.jl#L42-L47

where failure is always true. It works as expected if I change :Success to ReturnCode.Success. I am rather new to Julia and SciML so I can't really pin the underlying problem. 

I am using Julia 1.8.2 and DiffEqParamEstim 1.27.0. The minimal example based on the tutorial is

```julia
using RecursiveArrayTools
using DifferentialEquations, DiffEqParamEstim, JuMP, NLopt, Plots


function f(du,u,p,t)
    du[1] = dx = p[1]*u[1] - u[1]*u[2]
    du[2] = dy = -3*u[2] + u[1]*u[2]
  end
  
  u0 = [1.0;1.0]
  tspan = (0.0,10.0)
  p = [1.5]
  prob = ODEProblem(f,u0,tspan,p)

  sol = solve(prob,Tsit5())


t = collect(range(0,stop=10,length=200))
using RecursiveArrayTools # for VectorOfArray
randomized = VectorOfArray([(sol(t[i]) + .01randn(2)) for i in 1:length(t)])
data = convert(Array,randomized)

lossfun = L2Loss(t,data)

lossfun(sol)
```

**Comment by danilodurs** [comment] 2022-11-05 09:43
Hello
It seems like I got the same problem since I updated all my packages this week.
Downgrading DiffEqParamEstim to 1.26 or 1.25 does not seem to solve this issue. So I guess the source of the problem is elsewhere... 
Still trying to figure it out.


Julia version: 1.8.2
Packages:
[a134a8b2] BlackBoxOptim v0.6.2
[8d3b24bd] CMAEvolutionStrategy v0.2.5
[336ed68f] CSV v0.10.7
[479239e8] Catalyst v12.3.1
[861a8166] Combinatorics v1.0.2
[a93c6f00] DataFrames v1.4.2
[bcd4f6db] DelayDiffEq v5.38.3
[aae7a2af] DiffEqFlux v1.52.0
[1130ab10] DiffEqParamEstim v1.27.0
[0c46a032] DifferentialEquations v7.6.0
[31c24e10] Distributions v0.25.76
[89b67f3b] ExcelFiles v1.0.0
[587475ba] Flux v0.13.7
[38e38edf] GLM v1.8.1
[28b8d3ca] GR v0.69.5
[09f84164] HypothesisTests v0.10.11
[7073ff75] IJulia v1.23.3
[615f187c] IfElse v0.1.1
[a98d9a8b] Interpolations v0.14.6
[c8e1da08] IterTools v1.4.0
[ccbc3e58] JumpProcesses v9.2.2
[b964fa9f] LaTeXStrings v1.3.0
[23fbe1c1] Latexify v0.15.17
[93acb638] LikelihoodProfiler v0.5.0
[7ed4a6bd] LinearSolve v1.27.1
[442fdcdd] Measures v0.3.1
[961ee093] ModelingToolkit v8.31.0
[429524aa] Optim v1.7.3
[1dea7af3] OrdinaryDiffEq v6.30.1
[58dd65bb] Plotly v0.4.1
[a03496cd] PlotlyBase v0.8.19
[f0f68f2c] PlotlyJS v0.18.10
[f2990250] PlotlyKaleido v1.0.0
[91a5bcdd] Plots v1.35.8
[d330b81b] PyPlot v2.11.0
[1fd47b50] QuadGK v2.6.0
[731186ca] RecursiveArrayTools v2.32.1
[0bca4576] SciMLBase v1.68.1
[2913bbd2] StatsBase v0.33.21
[220ca800] StructuralIdentifiability v0.4.2
[78aadeae] SymbolicNumericIntegration v0.8.6
[d1185830] SymbolicUtils v0.19.11
[0c5d862f] Symbolics v4.13.0
[770da0de] UpdateJulia v0.4.0
[37e2e46d] LinearAlgebra
[9e88b42a] Serialization

**Comment by ChrisRackauckas** [comment] 2022-11-06 14:25
Fixed in https://github.com/SciML/DiffEqParamEstim.jl/pull/184

**Closed by ChrisRackauckas** 2022-11-06 14:25 UTC
